### ISSUE TITLE
unexpected keyword argument 'connection_class'

### ISSUE THREAD

**Issue by rajaravi1** [sebleier/django-redis-cache#181]
>>> from django.core.cache import cache
>>> cache.set('dfd', ['raja'])
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/api-3.6.6/lib/python3.6/site-packages/redis/client.py", line 823, in __del__
    self.close()
  File "/home/ubuntu/.pyenv/versions/api-3.6.6/lib/python3.6/site-packages/redis/client.py", line 826, in close
    conn = self.connection
AttributeError: 'Redis' object has no attribute 'connection'
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ubuntu/.pyenv/versions/api-3.6.6/lib/python3.6/site-packages/django/core/cache/__init__.py", line 99, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/home/ubuntu/.pyenv/versions/api-3.6.6/lib/python3.6/site-packages/django/core/cache/__init__.py", line 80, in __getitem__
    cache = _create_cache(alias)
  File "/home/ubuntu/.pyenv/versions/api-3.6.6/lib/python3.6/site-packages/django/core/cache/__init__.py", line 55, in _create_cache
    return backend_cls(location, params)
  File "/home/ubuntu/.pyenv/versions/api-3.6.6/lib/python3.6/site-packages/redis_cache/backends/single.py", line 21, in __init__
    client = self.create_client(server)
  File "/home/ubuntu/.pyenv/versions/api-3.6.6/lib/python3.6/site-packages/redis_cache/backends/base.py", line 186, in create_client
    client = self.Redis(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'connection_class'
>>>

Test script - 
==========
import redis

conn = redis.Redis(
        host='master.xxxx.rw1fiwa.usw3.cache.amazonaws.com',
        ssl=True,
        password='itsCacheTokenWorking')

print(conn)
print(conn.ping())

The above test script is working good because passing ssl=True

The reported error (unexpected keyword argument 'connection_class') occurs because django-redis-cache is trying to pass connection_class keyword argument to redis.Redis which is unsupported

I could see that there are fixes suggested: https://github.com/BureauxLocaux/django-redis-cache/commit/18ea61fe8defd8f5631227e0e75a14a5cb0a0c26 but wonder why that is not yet implemented/merged

**Comment by sebleier** [comment]
Sorry for delay.  This has been fixed in 2.1.1. Let me know if you have a problem.

**Comment by jdavisp3** [comment]
🚀 Thanks a ton @sebleier !
