### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by antonagestam** [sebleier/django-redis-cache#78]
Stumbled upon this syntax error using Python 3.4, probably because I didn't install hiredis.
```
Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/djcelery/management/commands/celery.py", line 23, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/celery/loaders/base.py", line 129, in init_worker
    self.on_worker_init()
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/djcelery/loaders.py", line 132, in on_worker_init
    self.close_cache()
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/djcelery/loaders.py", line 99, in close_cache
    cache.cache.close()
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/django/core/cache/__init__.py", line 131, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/django/core/cache/__init__.py", line 113, in __getitem__
    cache = _create_cache(alias)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/django/core/cache/__init__.py", line 84, in _create_cache
    backend_cls = import_string(backend)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/redis_cache/__init__.py", line 1, in <module>
    from redis_cache.backends.single import RedisCache
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/redis_cache/backends/single.py", line 7, in <module>
    from redis_cache.backends.base import BaseRedisCache
  File "/Users/antonagestam/.virtualenvs/5m-ia/lib/python3.4/site-packages/redis_cache/backends/base.py", line 108
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
```

**Comment by rhodges** [comment]
@antonagestam I also had this problem, particularly while running `manage migrate` with Python3.4
I ended up just forking your repo and making the fixes I needed to get around. This was the first break, which I fixed in a different way (having not seen your #78 fix).

The other was in sharder.py:
```
    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 354, in execute
        django.setup()
      File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 85, in populate
        app_config = AppConfig.create(entry)
      File "/usr/local/lib/python3.4/dist-packages/django/apps/config.py", line 87, in create
        module = import_module(entry)
      File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1448, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/usr/local/lib/python3.4/dist-packages/redis_cache/__init__.py", line 2, in <module>
        from redis_cache.backends.multiple import ShardedRedisCache
      File "/usr/local/lib/python3.4/dist-packages/redis_cache/backends/multiple.py", line 7, in <module>
        from redis_cache.sharder import HashRing
      File "/usr/local/lib/python3.4/dist-packages/redis_cache/sharder.py", line 7, in <module>
        DIGITS = int(log(sys.maxint) / log(16))
    AttributeError: 'module' object has no attribute 'maxint'
```
After reading http://stackoverflow.com/a/13795777 I changed sys.maxint to sys.maxsize in my edits here:
https://github.com/rhodges/django-redis-cache/commit/228e2fb3bdf3248d6f57ddbd79edcdfa564175ac 

That seemed to do the trick, but I haven't done any thorough testing to know if this breaks anything else. The edits are quick, or I can send you a pull request if you'd rather.

**Comment by sebleier** [comment]
I have a PR on the way, just a bit busy with work ATM.  I'll try and push it out in the next couple days.

**Comment by sebleier** [comment]
This is fixed in the latest release.
